#!/bin/bash

#Halton
make
mpirun -np 8 ./exp.exe -n 16 -t 0 -l 3

#Sobol
make
mpirun -np 8 ./exp.exe -n 16 -t 1 -l 5

#Sparse Grid
make
mpirun -np 8 ./exp.exe -n 16 -t 2 -l 7

#IPLR2
make
mpirun -np 8 ./exp.exe -n 16 -t 3 -l 10